baseURL: "https://cinnamongum.art/"
languageCode: en-us
title: Cinnamon Gum
theme: coyote

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 1
outputs:
  home:
    - HTML
    - JSON

imaging:
  anchor: Smart
  bgColor: "#ffffff"
  hint: photo
  quality: 10
  resampleFilter: Box

author:
  name: "Nuzhat Radia"
